# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: nv_domainsettings # Pflichtfeld
version: '1.1.0' # Pflichtfeld
author: novinet GmbH & Co KG
supportpage: https://github.com/novinet-git/nv_domainsettings

    
# Abhängigkeiten
# Anforderungen ans System oder anderere AddOns, um dieses AddOn installieren oder update zu können
requires:
    redaxo: '^5.5' # benötigt mindestens REDAXO 5.5
    packages:
        yrewrite: '^2.5' # benötigt mindestens das Addon YREWRITE 2.5
        yform: '^3.0' # benötigt mindestens das Addon YFORM 3.0
    php:
        version: '>=5.6' # benötigt mindestens PHP 5.6

